/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * llm-abyss API
 * ローカル LLM の Mechanistic Interpretability ツール
 * OpenAPI spec version: 0.1.0
 */
import { customFetch } from '../../client';

/**
 * @summary Health Check
 */
export type healthCheckApiHealthGetResponse200 = {
  data: unknown
  status: 200
}
    
export type healthCheckApiHealthGetResponseSuccess = (healthCheckApiHealthGetResponse200) & {
  headers: Headers;
};
;

export type healthCheckApiHealthGetResponse = (healthCheckApiHealthGetResponseSuccess)

export const getHealthCheckApiHealthGetUrl = () => {


  

  return `/api/health`
}

export const healthCheckApiHealthGet = async ( options?: RequestInit): Promise<healthCheckApiHealthGetResponse> => {
  
  return customFetch<healthCheckApiHealthGetResponse>(getHealthCheckApiHealthGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


