/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * llm-abyss API
 * ローカル LLM の Mechanistic Interpretability ツール
 * OpenAPI spec version: 0.1.0
 */
import type { AttentionRequestLayer } from './attentionRequestLayer';
import type { AttentionRequestHead } from './attentionRequestHead';

export interface AttentionRequest {
  /**
   * @minLength 1
   * @maxLength 1000
   */
  text: string;
  layer?: AttentionRequestLayer;
  head?: AttentionRequestHead;
}
