/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * llm-abyss API
 * ローカル LLM の Mechanistic Interpretability ツール
 * OpenAPI spec version: 0.1.0
 */
import type { DownloadedModelResponseSizeGb } from './downloadedModelResponseSizeGb';

export interface DownloadedModelResponse {
  id: string;
  name: string;
  size_gb?: DownloadedModelResponseSizeGb;
}
