/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * llm-abyss API
 * ローカル LLM の Mechanistic Interpretability ツール
 * OpenAPI spec version: 0.1.0
 */
import type { GenerationTokenResult } from './generationTokenResult';

export interface GenerationResponse {
  input_text: string;
  generated_text: string;
  tokens: GenerationTokenResult[];
}
