/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * llm-abyss API
 * ローカル LLM の Mechanistic Interpretability ツール
 * OpenAPI spec version: 0.1.0
 */

export interface GenerationRequest {
  /**
   * @minLength 1
   * @maxLength 500
   */
  text: string;
  /**
   * @minimum 1
   * @maximum 200
   */
  max_new_tokens?: number;
  /**
   * @minimum 0.01
   * @maximum 5
   */
  temperature?: number;
  /**
   * @minimum 1
   * @maximum 50
   */
  top_k_tokens?: number;
}
