/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * llm-abyss API
 * ローカル LLM の Mechanistic Interpretability ツール
 * OpenAPI spec version: 0.1.0
 */
import type { LogitLensLayerResultTopTokensItem } from './logitLensLayerResultTopTokensItem';

export interface LogitLensLayerResult {
  layer: number;
  top_tokens: LogitLensLayerResultTopTokensItem[];
}
