/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * llm-abyss API
 * ローカル LLM の Mechanistic Interpretability ツール
 * OpenAPI spec version: 0.1.0
 */

export interface ModelInfoResponse {
  id: string;
  name: string;
  params: string;
  n_layers: number;
  description: string;
  downloaded?: boolean;
}
