/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * llm-abyss API
 * ローカル LLM の Mechanistic Interpretability ツール
 * OpenAPI spec version: 0.1.0
 */
import type { ModelStatusResponseModelName } from './modelStatusResponseModelName';
import type { ModelStatusResponseModelInfo } from './modelStatusResponseModelInfo';
import type { ModelStatusResponseDevice } from './modelStatusResponseDevice';

export interface ModelStatusResponse {
  loaded: boolean;
  model_name?: ModelStatusResponseModelName;
  model_info?: ModelStatusResponseModelInfo;
  device?: ModelStatusResponseDevice;
}
