/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * llm-abyss API
 * ローカル LLM の Mechanistic Interpretability ツール
 * OpenAPI spec version: 0.1.0
 */

export interface NeuronsRequest {
  /**
   * @minLength 1
   * @maxLength 1000
   */
  text: string;
  layer: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  top_k?: number;
}
