/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * llm-abyss API
 * ローカル LLM の Mechanistic Interpretability ツール
 * OpenAPI spec version: 0.1.0
 */
import type {
  DownloadedModelResponse,
  HTTPValidationError,
  ModelInfoResponse,
  ModelLoadRequest,
  ModelStatusResponse
} from '../../model';

import { customFetch } from '../../client';

/**
 * 厳選モデルリストを返す。ダウンロード済みかどうかも付与。
 * @summary Get Available Models
 */
export type getAvailableModelsApiModelsAvailableGetResponse200 = {
  data: ModelInfoResponse[]
  status: 200
}
    
export type getAvailableModelsApiModelsAvailableGetResponseSuccess = (getAvailableModelsApiModelsAvailableGetResponse200) & {
  headers: Headers;
};
;

export type getAvailableModelsApiModelsAvailableGetResponse = (getAvailableModelsApiModelsAvailableGetResponseSuccess)

export const getGetAvailableModelsApiModelsAvailableGetUrl = () => {


  

  return `/api/models/available`
}

export const getAvailableModelsApiModelsAvailableGet = async ( options?: RequestInit): Promise<getAvailableModelsApiModelsAvailableGetResponse> => {
  
  return customFetch<getAvailableModelsApiModelsAvailableGetResponse>(getGetAvailableModelsApiModelsAvailableGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * ダウンロード済みモデル一覧。
 * @summary Get Downloaded
 */
export type getDownloadedApiModelsDownloadedGetResponse200 = {
  data: DownloadedModelResponse[]
  status: 200
}
    
export type getDownloadedApiModelsDownloadedGetResponseSuccess = (getDownloadedApiModelsDownloadedGetResponse200) & {
  headers: Headers;
};
;

export type getDownloadedApiModelsDownloadedGetResponse = (getDownloadedApiModelsDownloadedGetResponseSuccess)

export const getGetDownloadedApiModelsDownloadedGetUrl = () => {


  

  return `/api/models/downloaded`
}

export const getDownloadedApiModelsDownloadedGet = async ( options?: RequestInit): Promise<getDownloadedApiModelsDownloadedGetResponse> => {
  
  return customFetch<getDownloadedApiModelsDownloadedGetResponse>(getGetDownloadedApiModelsDownloadedGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * 現在ロード中のモデル状態。
 * @summary Get Model Status
 */
export type getModelStatusApiModelsStatusGetResponse200 = {
  data: ModelStatusResponse
  status: 200
}
    
export type getModelStatusApiModelsStatusGetResponseSuccess = (getModelStatusApiModelsStatusGetResponse200) & {
  headers: Headers;
};
;

export type getModelStatusApiModelsStatusGetResponse = (getModelStatusApiModelsStatusGetResponseSuccess)

export const getGetModelStatusApiModelsStatusGetUrl = () => {


  

  return `/api/models/status`
}

export const getModelStatusApiModelsStatusGet = async ( options?: RequestInit): Promise<getModelStatusApiModelsStatusGetResponse> => {
  
  return customFetch<getModelStatusApiModelsStatusGetResponse>(getGetModelStatusApiModelsStatusGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * モデルをメモリにロードする。
 * @summary Load Model
 */
export type loadModelApiModelsLoadPostResponse200 = {
  data: ModelStatusResponse
  status: 200
}

export type loadModelApiModelsLoadPostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type loadModelApiModelsLoadPostResponseSuccess = (loadModelApiModelsLoadPostResponse200) & {
  headers: Headers;
};
export type loadModelApiModelsLoadPostResponseError = (loadModelApiModelsLoadPostResponse422) & {
  headers: Headers;
};

export type loadModelApiModelsLoadPostResponse = (loadModelApiModelsLoadPostResponseSuccess | loadModelApiModelsLoadPostResponseError)

export const getLoadModelApiModelsLoadPostUrl = () => {


  

  return `/api/models/load`
}

export const loadModelApiModelsLoadPost = async (modelLoadRequest: ModelLoadRequest, options?: RequestInit): Promise<loadModelApiModelsLoadPostResponse> => {
  
  return customFetch<loadModelApiModelsLoadPostResponse>(getLoadModelApiModelsLoadPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      modelLoadRequest,)
  }
);}


/**
 * 現在のモデルをアンロードする。
 * @summary Unload Model
 */
export type unloadModelApiModelsUnloadPostResponse200 = {
  data: unknown
  status: 200
}
    
export type unloadModelApiModelsUnloadPostResponseSuccess = (unloadModelApiModelsUnloadPostResponse200) & {
  headers: Headers;
};
;

export type unloadModelApiModelsUnloadPostResponse = (unloadModelApiModelsUnloadPostResponseSuccess)

export const getUnloadModelApiModelsUnloadPostUrl = () => {


  

  return `/api/models/unload`
}

export const unloadModelApiModelsUnloadPost = async ( options?: RequestInit): Promise<unloadModelApiModelsUnloadPostResponse> => {
  
  return customFetch<unloadModelApiModelsUnloadPostResponse>(getUnloadModelApiModelsUnloadPostUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


/**
 * モデルをダウンロードする。SSE で進捗をストリーミング。
 * @summary Download Model
 */
export type downloadModelApiModelsDownloadModelNameGetResponse200 = {
  data: unknown
  status: 200
}

export type downloadModelApiModelsDownloadModelNameGetResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type downloadModelApiModelsDownloadModelNameGetResponseSuccess = (downloadModelApiModelsDownloadModelNameGetResponse200) & {
  headers: Headers;
};
export type downloadModelApiModelsDownloadModelNameGetResponseError = (downloadModelApiModelsDownloadModelNameGetResponse422) & {
  headers: Headers;
};

export type downloadModelApiModelsDownloadModelNameGetResponse = (downloadModelApiModelsDownloadModelNameGetResponseSuccess | downloadModelApiModelsDownloadModelNameGetResponseError)

export const getDownloadModelApiModelsDownloadModelNameGetUrl = (modelName: string,) => {


  

  return `/api/models/download/${modelName}`
}

export const downloadModelApiModelsDownloadModelNameGet = async (modelName: string, options?: RequestInit): Promise<downloadModelApiModelsDownloadModelNameGetResponse> => {
  
  return customFetch<downloadModelApiModelsDownloadModelNameGetResponse>(getDownloadModelApiModelsDownloadModelNameGetUrl(modelName),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


